### PR TITLE
bump Janet version to v1.34

### PR DESCRIPTION
**Pull request by AlecTroemel**
also removed the `strict: true` from the demo cart, which was incorrectly copy/pasted from the fennel demo cart.

### CODE REVIEW

**Comment by AlecTroemel** [comment]
took a minute to find the actual windows failure, heres the line https://github.com/nesbox/TIC-80/actions/runs/8853673596/job/24315055075?pr=2539#step:4:3165

```
janet.lib(janet.c.obj) : error LNK2019: unresolved external symbol InterlockedIncrement referenced in function janet_atomic_inc [D:\a\TIC-80\TIC-80\build\cart2prj.vcxproj]
```

**Comment by AlecTroemel** [comment]
from what I can tell that `InterlockedIncrement` function call has been around forever. My gut says this is something off with the build configuration

**Review by nesbox — APPROVED** [review]
we have problem with `InterlockedIncrement` on windows because ${THIRDPARTY_DIR}/janet/build/c/janet.c doesn't include `windows.h`
I approve it and later will create a workaround to fix this

**Comment by nesbox** [comment]
Unfortunately, I wasn't able to fix the Winxp build, a lot of errors.
image
So I reverted the PR for now to the old Janet version, sorry.

**Comment by AlecTroemel** [comment]
I'll chat with the Janet community!  I don't think we have any sort of automated builds for Windows, especially not windows XP.

Hopefully I'll be able to reproduce the Janet windows XP build errors independent of tic80

**Comment by AlecTroemel** [comment]
there are build & test ci/cd jobs for windows, just not windows XP https://github.com/janet-lang/janet/actions/runs/8777715785/job/24083063634?pr=1438

**Comment by nesbox** [comment]
I'm thinking of reopening PR and trying to fix the build separately

**Comment by Miguel-hrvs** [comment]
Latest janet from master branch now builds great in all windows platforms: https://github.com/Miguel-hrvs/TIC-80/actions/runs/11304129638/job/31442101819
